### PR TITLE
Add basic support for trufflehog

### PR DESCRIPTION
**Pull request by travisdonnell**
Executes basic high entropy trufflehog scan of the cloned repository. There are some quirks to how trufflehog outputs data, so the parsing looks kinda hacky. I'll probably revisit it at some point.

Included Dockfile update to install trufflehog.

There are some dead commits where i was adding and removing a fake high entropy string, but having a hard time wrapping by head around how rebasing works. If you'd like me to go back and take another crack at removing those from the commit history, let me know.

### CODE REVIEW

**Comment by jordan-wright** [comment]
Hey @travisdonnell,

Thank you for sending this in! Supporting truffleHog would be a wonderful addition to secret-bridge.

No worries about the multiple commits. Typically, when merging a PR we choose the option to squash all the commits into a single new commit, so those will get cleaned up with no problems. I'm not exactly sure why GitHub is saying there's a merge conflict with the README. If there's a way to resolve that on your end that'd be great. Otherwise, I should be able to fix those on my end.

I will likely have time over the next few days to take a pass at reviewing this and getting everything merged in. I'll keep you updated! Thanks again for taking the time to add this functionality, it's much appreciated!

**Comment by travisdonnell** [comment]
My commit was missing a docker note y'all added to the README. I've adopted your edits to resolve the conflict.

**Comment by nickmooney** [comment]
Thanks for this, @travisdonnell! truffleHog has a `--json` option which will remove the need to mess with all the special terminal control characters. We should be able to parse the JSON output directly.

Would you be willing to give that a shot and rewrite the PR?

Thanks for the consideration!
Nick

**Comment by travisdonnell** [comment]
Will do. The --json flag output didn't return a single object, but rather several completely separate payloads. Would need to either squash all output to a single object (maybe can just wrap with brackets? Will see), or change up how the json parser handles the object. I'll see what I can come up with.

**Comment by nickmooney** [comment]
Oh, that's sort of annoying. My immediate thought is just to split by blobs and then call the parser multiple times, but I'm not sure if there's anything specific to the format that would make that difficult.

**Comment by travisdonnell** [comment]
Ok, think I got it this time. Moved the json parsing logic from the larger object to after .splitlines() and handled it blob-by-blob. Luckily each object is separated by CRLF cleanly, so it looks to be working.

**Comment by nickmooney** [comment]
Looks good! I merged this PR into another branch so I could make a couple nitpicky editorial changes, mostly to the README -- a PR based on that branch (#7) has landed in `master`, and you should be credited for it. Thank you again!

**Pull request merged**
