### PR TITLE
Update read me with Docker Pull instruction

### PR DESCRIPTION
**Pull request by andreathniah**
This may seem trivial, but as someone new to docker, it took me a good half an hour before realizing `docker pull` was necessary.

### CODE REVIEW

**Comment by jordan-wright** [comment]
Hi @andreathniah,

Thanks for reaching out! I appreciate you sending this in. In our instructions, when we say "You can see how to run the Docker image in the Usage section below.", was it clear that we were referring to [this section](https://github.com/duo-labs/secret-bridge#running-via-docker) of the readme, or was that confusing? I ask because I can see that it might be hard to navigate so maybe we could just link to that section of the doc in the Readme instead?

I believe that by using `docker run`, the pull should happen automatically if the image isn't found locally so I'm not sure we should add the explicit step here. But, it sounds like there is confusion somewhere so I'd like to address it so it's more clear where to go for the Docker instructions.

Thanks again for getting in touch!

**Comment by andreathniah** [comment]
Hi @jordan-wright, that's weird, my initial command of `docker run` did not pull the image, but after trying it out again, you are right. 

I must admit I was rather confused and agree that linking to that section of the doc in README would be good. That said, I feel that a note about the image pull happening automatically if it isn't found locally should be included so new users like myself would know that `docker run` command is the only docker command they need to get the tool up and running.

Thank you and sorry for the confusion!

**Comment by jordan-wright** [comment]
Hi @andreathniah,

Thanks for the update! Would you like to update this PR to reflect the proposed changes to the README? I'm only asking, since we love seeing other contributors getting involved where possible. Otherwise, just let me know and I'd be happy to make the change myself when I get a chance.

**Comment by andreathniah** [comment]
@jordan-wright I will update the PR to reflect the changes!

**Comment by jordan-wright** [comment]
LGTM! Thank you so much for taking the time to send in those updates @andreathniah!

**Pull request merged**
